#include "neurox/Neurox.h"

#ifdef ADDITIONAL_MECHS
extern "C" {extern void modl_reg(void);} ///> generated by CMake in build/coreneuron/mod_func.c
#else
void modl_reg() {} ///No additional mechs, dont register any external
#endif

int main(int argc, char** argv)
{ 
    //register HPX methods
    NeuroX::registerHpxActions();
    NeuroX::Neuron::registerHpxActions();
    NeuroX::Branch::registerHpxActions();
    NeuroX::Mechanism::registerHpxActions();
    NeuroX::Solver::BackwardEuler::registerHpxActions();
    NeuroX::Solver::HinesSolver::registerHpxActions();

    //Init HPX
    if (hpx_init(&argc, &argv) != 0)
    {
        printf("HPX failed to initialize!\n");
        return 1;
    }
    printf("\nHPX started. Localities: %d, Threads/locality: %d\n", HPX_LOCALITIES, HPX_THREADS);

    //Run main
    int e = hpx_run(&NeuroX::main, argv, argc);

    //clean up
    hpx_finalize();
    return e;
}
